### SIGN UP 
POST http://localhost:3003/users/signup
Content-Type: application/json

{
    "name": "Celminha", 
    "email": "celminha@avengers.com", 
    "password": "123456"
}

###

### LOGIN
POST http://localhost:3003/users/login
Content-Type: application/json

{
    "email": "hulk-smash@avengers.com", 
    "password": "123456"
}

###

