// Teste de server
GET http://localhost:3003/ta-acordado?

###

// Fazer cadastro
POST http://localhost:3003/user/signup
Content-Type: application/json

{
    "email": "cap-america@mail.com",
    "password": "123456"
}

###

// Fazer login
POST http://localhost:3003/login
Content-Type: application/json

{
    "email": "meguinha@mail.com",
    "password": "1234"
}