// Teste de server
GET http://localhost:3003/ta-acordado?

###

//Criar usuário
PUT http://localhost:3003/user
Content-Type: application/json

{
    "name": "Meg", 
    "nickname": "skywalker", 
    "email": "meguinha@mail.com",
    "password": "123456"
}