// Criar usuário
PUT http://localhost:3003/user
Content-Type: application/json


{
    "name": "Mariah Carey",
    "nickname": "mari",
    "email":"mari@mail.com"
}

###

// Buscar usuário pelo id
GET http://localhost:3003/user/001

###

// Editar usuário
POST http://localhost:3003/user/edit/003
Content-Type: application/json

{
    "nickname":"ravi modificada 2"
}

###

// Criar tarefa
PUT http://localhost:3003/task
Content-Type: application/json


{
    "title": "dia 28",
    "description": "mês 10",
    "formatedDeadline": "28/10/2021",
    "creatorUserId": "006"
}

###

// Buscar tarefa pelo id

GET http://localhost:3003/task/2


