// Criar usuário
PUT http://localhost:3003/user
Content-Type: application/json

{
    "name": "Amelie",
    "nickname": ,
    "email":"amy2@mail.com"
};

###

// Buscar usuário pelo id
GET http://localhost:3003/user/001



