### SERVER TEST
GET http://localhost:3003/ta-acordado?

### REGISTER
POST http://localhost:3003/signup
Content-Type: application/json

{
    "name": "Julia Roberts",
    "email": "juju@gmail.com",
    "password": "123456",
    "role": "NORMAL"
}

###

### LOGIN
POST http://localhost:3003/login
Content-Type: application/json

{
    "email": "juju@gmail.com",
    "password": "123456"
}

###

### RETRIEVE LOGGED USER DATA
GET http://localhost:3003/user/profile
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjgyZDAzMWMwLTYwODMtNDFjYS1hYWNlLThiZmU4MzdjNzQ1OCIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTYyMzU0MDM1MSwiZXhwIjoxNjU1MDk3OTUxfQ.DckGI8maBR0P5VL5FsfbP43byWooH9O-SuIiVuFPFTc 

###

### SEARCH USER BY ID
GET http://localhost:3003/user/610633fd-f4a5-4bf0-bbc3-0e4bcdca1405
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRlZTNlMjMzLTYxMWMtNGQ2MC1hMjk1LWE1ODdkMDY2Nzc2NSIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2MjM2MTI3NzUsImV4cCI6MTY1NTE3MDM3NX0.1q9D_OZRabuBeQN2XYqJvxCXRTlsk5euSGkCygBpkpc

###

### ADD RECIPE
POST http://localhost:3003/recipe
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRlZTNlMjMzLTYxMWMtNGQ2MC1hMjk1LWE1ODdkMDY2Nzc2NSIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2MjM2MTYzMjYsImV4cCI6MTY1NTE3MzkyNn0.uwU6Z7KYCgfUcos3vbdE8wLOBXNRhQAJHxLVJ3H10gs

{
    "title": "Receita 3 Julia",
    "description": "3"
}

###

### SEARCH RECIPE BY ID
GET http://localhost:3003/recipe/00e75814-3ea8-42c2-8e7b-3e579f65060e
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjgwZTExYjA2LWUyNzEtNGM1My05YzBhLTg2YTdhMTY4Mzc3OSIsImlhdCI6MTYyMzQxNjg1OCwiZXhwIjoxNjU0OTc0NDU4fQ.7UkFw_yZoUIaiDOHB9s0lJN4saqr7dIfjzxi__ltcag

###

### FOLLOW USER
POST http://localhost:3003/user/follow
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRlZTNlMjMzLTYxMWMtNGQ2MC1hMjk1LWE1ODdkMDY2Nzc2NSIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2MjM2MTc0MTIsImV4cCI6MTY1NTE3NTAxMn0.hDgFhlw_8N5VNQahEoYB-5H7CyNSnrY1N6DLJnGy0v8

{
    "followed_id": "5c84b166-6aad-452e-bee3-52c1e18b7e2b"
}

###

### UNFOLLOW USER
POST http://localhost:3003/user/unfollow
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRlZTNlMjMzLTYxMWMtNGQ2MC1hMjk1LWE1ODdkMDY2Nzc2NSIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2MjM2MTc1MzEsImV4cCI6MTY1NTE3NTEzMX0.P33eIGN5reYTyN7pFlpnJYKVyOvHJFMMmbRIThd9VKw

{
    "followed_id": "5c84b166-6aad-452e-bee3-52c1e18b7e2b"
}

###

### GET FEED
GET http://localhost:3003/feed
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImVlYzFjNzc4LWY3NDctNDYzYy05MTNiLTMyYzQ3MTUzMGEwNiIsImlhdCI6MTYyMzQ0NzcyNSwiZXhwIjoxNjU1MDA1MzI1fQ.BRjnATWj4f0YvP2RldWgVk6dau2VDAVfvwgu8yyAp4M

###

### EDIT RECIPE
POST http://localhost:3003/recipe/edit/00e75814-3ea8-42c2-8e7b-3e579f65060e
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRlZTNlMjMzLTYxMWMtNGQ2MC1hMjk1LWE1ODdkMDY2Nzc2NSIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2MjM2MTgyMDksImV4cCI6MTY1NTE3NTgwOX0.rzjpE-xEUaZG7OConeRoEBD58DGVKZRdzv2ueytwr-8

{
    "title": "RECEITA 1 JULIA EDITADA",
    "description": "EDITADA"
}

###

### DELETE RECIPE
DELETE http://localhost:3003/recipe/delete/711aa7dd-93c2-430a-972e-ee04c4cc2366
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRlZTNlMjMzLTYxMWMtNGQ2MC1hMjk1LWE1ODdkMDY2Nzc2NSIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2MjM2MTkwODcsImV4cCI6MTY1NTE3NjY4N30.s-JBaQY99Y4rF53p1RsgFcDqhCT9n1kSaUDZA85wU84

###

### DELETE ALL RECIPES BY USER ID
DELETE http://localhost:3003/recipes/delete/all/user/4ee3e233-611c-4d60-a295-a587d0667765
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRlZTNlMjMzLTYxMWMtNGQ2MC1hMjk1LWE1ODdkMDY2Nzc2NSIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2MjM2MjA5MjQsImV4cCI6MTY1NTE3ODUyNH0.T6wBesvBk7kUAOT9P8_5WvRFcyOJrdKlKsB-QiuIQW4

###

### DELETE USER (ADMIN)
DELETE http://localhost:3003/admin/delete/user/cf2c97d9-f5fe-4ec6-89dc-cc4cedaa2133
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjgyZDAzMWMwLTYwODMtNDFjYS1hYWNlLThiZmU4MzdjNzQ1OCIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTYyMzU0MDM1MSwiZXhwIjoxNjU1MDk3OTUxfQ.DckGI8maBR0P5VL5FsfbP43byWooH9O-SuIiVuFPFTc

###

### RESET PASSWORD
POST http://localhost:3003/user/password/reset
Content-Type: application/json

{
    "email": "lele.dev.test@gmail.com" 
}

###