### SERVER TEST
GET http://localhost:3003/ta-acordado?

### REGISTER
POST http://localhost:3003/signup
Content-Type: application/json

{
    "name": "Julia Roberts",
    "email": "juju@gmail.com",
    "password": "123456",
    "role": "NORMAL"
}

###

### LOGIN
POST http://localhost:3003/login
Content-Type: application/json

{
    "email": "maria@mail.com",
    "password": "123456"
}

###

### RETRIEVE LOGGED USER DATA
GET http://localhost:3003/user/profile
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNmMmM5N2Q5LWY1ZmUtNGVjNi04OWRjLWNjNGNlZGFhMjEzMyIsInJvbGUiOiJTVFVERU5UIiwiaWF0IjoxNjIzNjEzNzYwLCJleHAiOjE2NTUxNzEzNjB9.UCLXHfrRGmcrumF76RJQv4MO26E6kpqVm0lKR-5JT4s

###

### SEARCH USER BY ID
GET http://localhost:3003/user/610633fd-f4a5-4bf0-bbc3-0e4bcdca1405
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRlZTNlMjMzLTYxMWMtNGQ2MC1hMjk1LWE1ODdkMDY2Nzc2NSIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2MjM2MTI3NzUsImV4cCI6MTY1NTE3MDM3NX0.1q9D_OZRabuBeQN2XYqJvxCXRTlsk5euSGkCygBpkpc

###

// Adicionar receitas
POST http://localhost:3003/recipe
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImVlYzFjNzc4LWY3NDctNDYzYy05MTNiLTMyYzQ3MTUzMGEwNiIsInJvbGUiOiJTVFVERU5UIiwiaWF0IjoxNjIzNTk1NzUyLCJleHAiOjE2NTUxNTMzNTJ9.p2jIoikRoQYQPN79JS4bRXtkEeyoULsAy7V4e_uYZRo

{
    "title": "Receita 2 Jorgim",
    "description": "2"
}

###

// Pesquisa receita pelo id
GET http://localhost:3003/recipe/1b6a47d7-f2cb-4e08-bd8d-08ecfdc7eb59
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjgwZTExYjA2LWUyNzEtNGM1My05YzBhLTg2YTdhMTY4Mzc3OSIsImlhdCI6MTYyMzQxNjg1OCwiZXhwIjoxNjU0OTc0NDU4fQ.7UkFw_yZoUIaiDOHB9s0lJN4saqr7dIfjzxi__ltcag

###

// Seguir usuário
POST http://localhost:3003/user/follow
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjgwZTExYjA2LWUyNzEtNGM1My05YzBhLTg2YTdhMTY4Mzc3OSIsInJvbGUiOiJTVFVERU5UIiwiaWF0IjoxNjIzNTk2NDI2LCJleHAiOjE2NTUxNTQwMjZ9.WoNHM6fKykYIIkphfCA_C6V9OSKnLPzy1xBSlcae16g

{
    "followed_id": "80e11b06-e271-4c53-9c0a-86a7a1683779"
}

###

// Deixar de seguir usuário
POST http://localhost:3003/user/unfollow
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjgwZTExYjA2LWUyNzEtNGM1My05YzBhLTg2YTdhMTY4Mzc3OSIsInJvbGUiOiJTVFVERU5UIiwiaWF0IjoxNjIzNTk2NjE2LCJleHAiOjE2NTUxNTQyMTZ9.anv_uhwv3zOOtUj-3k18X8xXPlv3AXBl5f0Jo83QIew

{
    "followed_id": "cf2c97d9-f5fe-4ec6-89dc-cc4cedaa2133"
}

###

// Trazer feed de receitas
GET http://localhost:3003/user/feed
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImVlYzFjNzc4LWY3NDctNDYzYy05MTNiLTMyYzQ3MTUzMGEwNiIsImlhdCI6MTYyMzQ0NzcyNSwiZXhwIjoxNjU1MDA1MzI1fQ.BRjnATWj4f0YvP2RldWgVk6dau2VDAVfvwgu8yyAp4M

###

// Editar receita
POST http://localhost:3003/recipe/edit/11dc0f66-1f1f-4586-a3b2-95586b47d7ed
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjgwZTExYjA2LWUyNzEtNGM1My05YzBhLTg2YTdhMTY4Mzc3OSIsInJvbGUiOiJTVFVERU5UIiwiaWF0IjoxNjIzNTA3MjUyLCJleHAiOjE2NTUwNjQ4NTJ9.pUdA03OtqEedHW3z5Odd675YmH3pbU-P4zrOs-JSIJw

{
    "title": "SALADA DE FRUTAS EDITADA!",
    "description": "EDITANDO ALGO AUTORIZADO"
}

###

// Deletar receita (NORMAL/ADMIN)
DELETE http://localhost:3003/recipe/delete/d19b5d1a-8638-47d0-acbf-658ac03b3241
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjgyZDAzMWMwLTYwODMtNDFjYS1hYWNlLThiZmU4MzdjNzQ1OCIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTYyMzUzNjI2NCwiZXhwIjoxNjU1MDkzODY0fQ.gbEd1d2sVhCgnnJm9PU9eq4aYmr7TO_5tF_nFuOSyyI

###

// Deletar todas as receitas de um usuário pelo id dele
DELETE http://localhost:3003/recipes/delete/all/user/eec1c778-f747-463c-913b-32c471530a06
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImVlYzFjNzc4LWY3NDctNDYzYy05MTNiLTMyYzQ3MTUzMGEwNiIsInJvbGUiOiJTVFVERU5UIiwiaWF0IjoxNjIzNTk0MjAzLCJleHAiOjE2NTUxNTE4MDN9.OGjtI5dNz3hEKQ76a1jhcVeGcNyG7bqnWUdPyWqLgmk

###

// Deletar usuário (ADMIN)
DELETE http://localhost:3003/admin/delete/user/80e11b06-e271-4c53-9c0a-86a7a1683779
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjgyZDAzMWMwLTYwODMtNDFjYS1hYWNlLThiZmU4MzdjNzQ1OCIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTYyMzU0MDM1MSwiZXhwIjoxNjU1MDk3OTUxfQ.DckGI8maBR0P5VL5FsfbP43byWooH9O-SuIiVuFPFTc

###

// Reset password
POST http://localhost:3003/user/password/reset
Content-Type: application/json

{
    "email": "lele.dev.test@gmail.com" 
}