// Teste de server
GET http://localhost:3003/ta-acordado?

###

// Fazer cadastro
POST http://localhost:3003/user/signup
Content-Type: application/json

{
    "email": "teste6@mail.com",
    "password": "145535754",
    "role": "ADMIN"
}

###

// Fazer login
POST http://localhost:3003/user/login
Content-Type: application/json

{
    "email": "teste6@mail.com",
    "password": "145535754"
}

###

// Pesquisar usuário pelo email
GET http://localhost:3003/user?email=me

###

// Retorna as informações do usuário logado
GET http://localhost:3003/user/profile
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE4MTJhMDc2LTlhOTktNDYzMy04ZTY3LTI2NjA1OTdhMTg3NCIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTYyMzIwMjg4OCwiZXhwIjoxNjU0NzYwNDg4fQ.vCww1HfDE-5VszSDZu03dSdKmXXtR6awzXPE_ueF3ko