### SIGN UP
POST http://localhost:3003/signup
Content-Type: application/json

{   
    "name": "Tony Stark",
    "email": "stark-millionaire@avengers.com",
    "password": "123456",
    "role": "NORMAL"
}

###

### LOGIN
POST http://localhost:3003/login
Content-Type: application/json

{
    "email": "nino@mail.com",
    "password": "123456"
}

###